apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-checks
spec:
  analyzers:
    - deploymentStatus:
        strict: true
        name: linkerd-destination
        namespace: linkerd
        outcomes:
          - fail:
              when: "< 1"
              message: The linkerd-destination deployment does not have any ready replicas.
          - pass:
              when: "= 1"
              message: The linkerd-destination deployment is present.
    - deploymentStatus:
        strict: true
        name: linkerd-identity
        namespace: linkerd
        outcomes:
          - fail:
              when: "< 1"
              message: The linkerd-identity deployment does not have any ready replicas.
          - pass:
              when: "= 1"
              message: The linkerd-identity deployment is present.
    - deploymentStatus:
        strict: true
        name: linkerd-proxy-injector
        namespace: linkerd
        outcomes:
          - fail:
              when: "< 1"
              message: The linkerd-proxy-injector deployment does not have any ready replicas.
          - pass:
              when: "= 1"
              message: The linkerd-proxy-injector deployment is present.
- clusterPodStatuses:
        strict: true
        name: unhealthy
        namespaces:
          - linkerd
        outcomes:
          - fail:
              when: "== CrashLoopBackOff"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a CrashLoopBackOff state.
          - fail:
              when: "== ImagePullBackOff"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a ImagePullBackOff state.
          - fail:
              when: "== Pending"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a Pending state.
          - fail:
              when: "== Evicted"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a Evicted state.
          - fail:
              when: "== Terminating"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a Terminating state.
          - fail:
              when: "== Init:Error"
              message: Pod {{ .Namespace }}/{{ .Name }} is in an Init:Error state.
          - fail:
              when: "== Init:CrashLoopBackOff"
              message: Pod {{ .Namespace }}/{{ .Name }} is in an Init:CrashLoopBackOff state.
          - fail:
              when: "!= Healthy" # Catch all unhealthy pods. A pod is considered healthy if it has a status of Completed, or Running and all of its containers are ready.
              message: Pod {{ .Namespace }}/{{ .Name }} is unhealthy with a status of {{ .Status.Reason }}.
