apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-checks
spec:
  analyzers:
    - customResourceDefinition:
        strict: true
        customResourceDefinitionName: istiooperators.install.istio.io
        outcomes:
          - fail:
              message: The istiooperators CRD was not found in the cluster.
          - pass:
              message: istiooperators CRD is installed and available.
    - deploymentStatus:
        strict: true
        name: istiod
        namespace: istio-system
        outcomes:
          - fail:
              when: "< 1"
              message: The istiod deployment is not present.
          - pass:
              when: "= 1"
              message: The istiod deployment is present.
     - deploymentStatus:
        strict: true
        name: istio-egressgateway
        namespace: istio-system
        outcomes:
          - fail:
              when: "< 1"
              message: The istio-egressgateway deployment is not present.
          - pass:
              when: "= 1"
              message: The istio-egressgateway deployment is present.
    - deploymentStatus:
        strict: true
        name: istio-ingressgateway
        namespace: istio-system
        outcomes:
          - fail:
              when: "< 1"
              message: The istio-ingressgateway deployment is not present.
          - pass:
              when: "= 1"
              message: The istio-ingressgateway deployment is present.
    - clusterPodStatuses:
        strict: true
        name: unhealthy
        namespaces:
          - istio-system
        outcomes:
          - fail:
              when: "== CrashLoopBackOff"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a CrashLoopBackOff state.
          - fail:
              when: "== ImagePullBackOff"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a ImagePullBackOff state.
          - fail:
              when: "== Pending"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a Pending state.
          - fail:
              when: "== Evicted"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a Evicted state.
          - fail:
              when: "== Terminating"
              message: Pod {{ .Namespace }}/{{ .Name }} is in a Terminating state.
          - fail:
              when: "== Init:Error"
              message: Pod {{ .Namespace }}/{{ .Name }} is in an Init:Error state.
          - fail:
              when: "== Init:CrashLoopBackOff"
              message: Pod {{ .Namespace }}/{{ .Name }} is in an Init:CrashLoopBackOff state.
          - fail:
              when: "!= Healthy" # Catch all unhealthy pods. A pod is considered healthy if it has a status of Completed, or Running and all of its containers are ready.
              message: Pod {{ .Namespace }}/{{ .Name }} is unhealthy with a status of {{ .Status.Reason }}.
